# Recreating a plesk ubuntu server setup
# We need LAMP, subversion, git(?)
# We need all the WordPress plugins
# @link https://www.digitalocean.com/community/tutorials/how-to-automate-installing-wordpress-on-ubuntu-14-04-using-ansible
- hosts: all

  roles:
    - server
    - php
    - mysql
    - wordpress
